version: '3'

services:

  front:
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn watch
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:8080"